version: 0.2

phases:
  install:
    commands:    
      - echo Configuring AWS CLI credentials and default region
      - SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id $SECRET_ID)
      - MY_ACCESS_KEY=$(echo $SECRET_JSON | jq -r '.SecretString' | jq -r '.mySecretKey')
      - MY_SECRET_ACCES_KEY=$(echo $SECRET_JSON | jq -r '.SecretString' | jq -r '.mySecretKey')
      - aws configure set aws_access_key_id echo $MY_SECRET_ACCES_KEY
      - aws configure set aws_secret_access_key echo $MY_ACCESS_KEY
      - aws configure set default.region us-east-1
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 435326705105.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image
      - docker build --no-cache -t candidates:latest -f Dockerfile .
      - docker tag candidates:latest 435326705105.dkr.ecr.us-east-1.amazonaws.com/candidates:latest
      - docker push 435326705105.dkr.ecr.us-east-1.amazonaws.com/candidates:latest
  post_build:
    commands:
artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
    - imageDetail.json