version: 0.2

env:
    parameter-store:
        AWS_ACCESS_KEY_ID_PARAM: /CodeBuild/AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY_PARAM: /CodeBuild/AWS_SECRET_ACCESS_KEY

phases:
  install:
    commands:
      - echo Configuring AWS CLI credentials and default region
      - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PARAM
      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PARAM
      - aws configure set default.region us-east-1
  pre_build:
    commands:
      - sudo apt-get update -y
      - curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.28.1/2023-09-14/bin/darwin/amd64/kubectl
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
      - echo 'export PATH=$HOME/bin:$PATH' >> ~/.bash_candidates
      - echo Logging in to Amazon ECR
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 435326705105.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Applying Kubernetes service definition
      - aws eks update-kubeconfig --name cluster-microservices --region us-east-1
      - kubectl apply -f k8s-service.yml
      - kubectl rollout restart deployment/candidates-pod
  post_build:
    commands:
artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
    - imageDetail.json
    - k8s-service.yaml